export const copy = {
  title: 'LinkSense · AI 工作空间', brand: 'LinkSense', tagline: '为想法，留出空间', demo: '概念演示',
  overview: '工作总览', studio: '创意工作室', resources: '成果与资料', automations: '持续运行',
  workspace: '工作空间', personal: '个人空间', search: '搜索空间、成果或操作', searchShort: '搜索',
  newWork: '开始一件新工作', creative: '创意与设计', campaign: '秋日创意计划',
  projectDescription: '让一个小小的想法，成为可以看见的作品。',
  object: '鳄鱼的四季骑行', objectSub: '一段关于出发、季节与微风的循环动画',
  brief: '创作说明', notes: '灵感笔记', reference: '角色与配色参考',
  connected: '空间已就绪', account: '我的工作空间',
  saved: '已保存在演示中', draft: '有未保存的调整', preview: '作品', history: '版本',
  focus: '专注预览', exitFocus: '退出专注', export: '下载静态图', save: '保存版本',
  live: '实时预览', pause: '暂停', play: '播放', normal: '正常', slow: '慢速', fast: '快速',
  spring: '春日', summer: '盛夏', autumn: '秋天', winter: '冬日',
  season: '季节', speed: '骑行速度', sceneTitle: '一路，都是好风景。', sceneSub: '四 季 之 间 · 自 在 骑 行',
  selection: '当前作品', selectBackground: '选中背景', background: '动画背景',
  selectedHint: '已选中背景，接下来的指令会围绕它展开。',
  related: '这件工作里的内容', openBrief: '查看创作说明', ready: '已完成', working: '进行中',
  briefSub: '故事方向 · 视觉基调', notesSub: '3 个想法 · 持续积累',
  collaborate: '一起创作', context: '参考内容', activity: '进展', hidePanel: '收起协作面板', showPanel: '展开协作面板',
  assistant: 'LinkSense', assistantMeta: '陪你把想法做出来',
  welcome: '四季骑行已经准备好了。你可以直接体验作品，也可以选中背景，告诉我想怎么调整。',
  doneTitle: '这一版完成了', doneOne: '四种季节的场景与配色', doneTwo: '轻盈的循环骑行动画', doneThree: '随时可调的播放速度',
  suggestionTitle: '接下来，试着让它更像你', suggestAutumn: '换成秋天，骑得慢一点', suggestWinter: '试试安静的冬天',
  scope: '作用于', placeholder: '你想怎样调整这件作品？', send: '应用指令',
  demoHint: '演示支持季节与速度调整', updateReply: '已调整为「{{season}}」，速度为「{{speed}}」。预览已更新，可保存为新版本。',
  unsupported: '这个演示可以调整四季与骑行速度。试试“换成冬天”或“骑得慢一点”。', emptyInput: '先写下你想调整的内容。',
  savedReply: '已保存为 {{version}}。你可以在版本列表中回看。',
  versionSelected: '正在查看 {{version}}。', versionNote: '选择版本，回到当时的作品。',
  v1: '第一缕春风', v2: '在盛夏出发', v3: '秋日慢游', customVersion: '新的风景', current: '当前',
  activityOne: '四季版本已完成', activityTwo: '加入速度控制', activityThree: '确定角色与构图',
  justNow: '刚刚', beforeFive: '5 分钟前', beforeTwelve: '12 分钟前',
  contextDescription: 'AI 围绕当前作品，参考这些内容。', contextScope: '当前空间内可用',
  contextBrief: '轻松、治愈，适合循环播放。主角是一只骑自行车的小鳄鱼，用季节变化表达旅途中的不同心情。',
  contextNotes: '柔和的纸感色彩、几何山丘、清晰的角色轮廓。保持画面留白，让作品可以自在呼吸。',
  contextReference: '苔藓绿的角色、奶油色的天空，以及一点明亮的橘红。',
  homeEyebrow: '你的空间，正在生长', greeting: '想法在这里，慢慢成形。', homeSubtitle: '继续手边的创作，或把下一件事交给 LinkSense。',
  attention: '需要你看一眼', attentionTitle: '四季骑行，等你定稿', attentionText: '三个版本已准备好，打开作品选出喜欢的方向。', review: '查看作品',
  continuing: '继续上次的工作', spaceNote: '1 个空间 · 3 项内容', runningTitle: '事情，也可以持续向前。',
  runningSubtitle: '让固定的工作按计划进行，把注意力留给新的想法。', routine: '每周创意回顾',
  routineDesc: '汇总本空间的新作品与待办，准备一份每周回顾。', schedule: '每周五 · 17:00', enabled: '已开启', disabled: '已暂停',
  routineHint: '此处仅演示计划开关，不会实际运行或发送通知。',
  libraryTitle: '好想法，都有迹可循。', librarySubtitle: '作品、说明和灵感，在同一个空间里彼此连接。',
  fileType: '循环动画', docType: '文档', noteType: '笔记',
  searchHint: '快速到达你想继续的地方', noResults: '没有找到匹配内容，试试“作品”或“总览”。', close: '关闭',
  quickStart: '从这个创意开始', quickText: '在这个演示中，我们用“四季骑行”体验从想法到作品的过程。',
  mobileMenu: '打开导航', back: '返回作品', footer: '工作有了自己的空间。',
};
