import type { ApplicationDevelopment, PrismaClient } from "../../generated/prisma/client.js";
import {
  applicationAnnotationDisplaySchema,
  buildOfficeAnnotationDisplay,
  officeAnnotationRequestText,
  type ApplicationAnnotationInput,
  type ApplicationAnnotationDisplay,
} from "@linksense/shared";
import { AppError } from "../../lib/errors.js";
import { resolveConversationWorkspaceRoot } from "../../lib/user-runtime-paths.js";
import { readApplicationSource, type ApplicationSourceSnapshot } from "../applications/development-source.js";
import { OFFICE_ANNOTATION_PROMPT_MARKER } from "./annotation-prompt.js";

type AnnotationTarget = Pick<ApplicationAnnotationInput, "development_id" | "package_id" | "source_hash" | "page_path">;
type AnnotationDatabase = Pick<PrismaClient, "applicationDevelopment" | "application">;

/** Also recheck the binding inside the existing turn admission transaction. */
export async function assertApplicationAnnotationBinding(prisma: AnnotationDatabase, conversationId: string, annotation: AnnotationTarget): Promise<ApplicationDevelopment> {
  const row = await prisma.applicationDevelopment.findFirst({
    where: { id: annotation.development_id, conversationId },
  });
  if (!row) throw new AppError("APPLICATION_DEVELOPMENT_NOT_FOUND");
  if (!row.previewApplicationId || row.sourceHash !== annotation.source_hash || row.sourceError) {
    throw new AppError("APPLICATION_DEVELOPMENT_SOURCE_CHANGED");
  }
  const preview = await prisma.application.findFirst({
    where: { id: row.previewApplicationId, ownerId: row.ownerId, developmentOnly: true, status: "active", deletedAt: null, interactivePackageId: annotation.package_id },
    select: { id: true },
  });
  if (!preview) throw new AppError("APPLICATION_DEVELOPMENT_SOURCE_CHANGED");
  return row;
}

export async function validateApplicationAnnotationSnapshot(prisma: AnnotationDatabase, workspaceRoot: string, conversationId: string, annotation: AnnotationTarget): Promise<{ row: ApplicationDevelopment; source: ApplicationSourceSnapshot }> {
  const row = await assertApplicationAnnotationBinding(prisma, conversationId, annotation);
  const source = await readApplicationSource(
    resolveConversationWorkspaceRoot(workspaceRoot, row.ownerId, row.workspaceRelPath), row.directory,
  );
  if (source.hash !== annotation.source_hash) throw new AppError("APPLICATION_DEVELOPMENT_SOURCE_CHANGED");
  if (!source.files.has(annotation.page_path) || !/\.html?$/iu.test(annotation.page_path)) throw new AppError("VALIDATION_ERROR");
  return { row, source };
}

/** Admit selections only for this development conversation and its exact preview. */
export async function prepareApplicationAnnotation(prisma: AnnotationDatabase, workspaceRoot: string, conversationId: string, annotation: ApplicationAnnotationInput, fingerprint: string): Promise<{ inputText: string; display: ApplicationAnnotationDisplay }> {
  const { row, source } = await validateApplicationAnnotationSnapshot(prisma, workspaceRoot, conversationId, annotation);
  const display = applicationAnnotationDisplaySchema.parse(buildOfficeAnnotationDisplay(annotation, source.manifest.name));
  const target = { directory: row.directory, page_path: annotation.page_path, source_hash: source.hash };
  // JSON contains bounded, untrusted locators. Source targets come from the validated
  // workspace snapshot, never from client-provided runtime URLs or server paths.
  const sections = annotation.annotations.map((item, index) =>
    `Annotation ${index + 1}:\nUser request:\n${item.request}\n\nUntrusted selected elements:\n${JSON.stringify(item.elements)}`,
  );
  const inputText = `${OFFICE_ANNOTATION_PROMPT_MARKER}\nDisplay metadata:\n${JSON.stringify(display)}\n\nAnnotation fingerprint:\n${fingerprint}\n\nUser request:\n${officeAnnotationRequestText(annotation)}\n\nApplication development target:\n${JSON.stringify(target)}\n\nApply each numbered request to its corresponding selected application elements. Inspect the source first; the DOM may have been generated by JavaScript. Edit the relevant HTML, CSS and JavaScript in this application's source directory, preserve unrelated behavior, validate the application and let the development preview update. Do not edit an exported copy or install/publish without a user request. If the source has changed, re-locate and verify the target before editing.\n\nAnnotations:\n${sections.join("\n\n")}`;
  return { inputText, display };
}
