import { describe, expect, it } from "vitest"

import type { Conversation, ConversationFile } from "@/api/contracts"
import {
  findFirstCompletedTurnPreviewFile,
  findUpdatedOfficePreviewFile,
  getConversationFiles,
} from "@/features/conversations/conversation-office-preview-update"

function file(
  id: string,
  name: string,
  options: Partial<ConversationFile> = {}
): ConversationFile {
  return {
    id,
    name,
    mime_type: "text/html",
    kind: "artifact",
    size: 0,
    download_available: true,
    ...options,
  }
}

describe("conversation office preview updates", () => {
  it("finds the newest compatible artifact created after an annotated preview", () => {
    const source = file("source", "deck.html")
    const first = file("first", "deck (draft).html")
    const latest = file("latest", "deck (revised).html")

    expect(
      findUpdatedOfficePreviewFile({
        sourceFile: source,
        knownFileIds: [source.id],
        files: [source, first, latest],
      })
    ).toBe(latest)
  })

  it("does not surface existing, unrelated, or incompatible files", () => {
    const source = file("source", "deck.html")
    expect(
      findUpdatedOfficePreviewFile({
        sourceFile: source,
        knownFileIds: [source.id, "existing"],
        files: [
          source,
          file("existing", "deck (old).html"),
          file("word", "brief.docx", {
            mime_type:
              "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
          }),
          file("attachment", "page.html", { kind: "attachment" }),
        ],
      })
    ).toBeNull()
  })

  it("finds a replacement for a read-only code preview", () => {
    const source = file("source", "dashboard.ts", {
      mime_type: "text/plain",
    })
    const latest = file("latest", "dashboard (revised).ts", {
      mime_type: "text/plain",
    })

    expect(
      findUpdatedOfficePreviewFile({
        sourceFile: source,
        knownFileIds: [source.id],
        files: [source, latest],
      })
    ).toBe(latest)
  })

  it("collects message artifacts and removes duplicate ids", () => {
    const artifact = file("artifact", "deck.html")
    const conversation = {
      attachments: [file("attachment", "source.html", { kind: "attachment" })],
      artifacts: [artifact],
      messages: [{ attachments: [], artifacts: [artifact] }],
    } as unknown as Conversation

    expect(getConversationFiles(conversation).map((item) => item.id)).toEqual([
      "attachment",
      "artifact",
    ])
  })

  it("selects the earliest previewable file generated by the completed turn", () => {
    const first = file("first", "first.pdf", {
      turn_id: "current-turn",
      created_at: "2026-09-23T10:00:00.000Z",
    })
    const later = file("later", "later.pdf", {
      turn_id: "current-turn",
      created_at: "2026-09-23T10:01:00.000Z",
    })
    const conversation = {
      turns: [{ id: "current-turn", status: "completed" }],
      attachments: [
        file("attachment", "input.pdf", {
          kind: "attachment",
          turn_id: "current-turn",
        }),
      ],
      artifacts: [later, file("old", "old.pdf", { turn_id: "old-turn" })],
      messages: [{ artifacts: [first] }],
    } as unknown as Conversation

    expect(
      findFirstCompletedTurnPreviewFile(conversation, "current-turn")
    ).toBe(first)
  })

  it("skips unavailable or unsupported files and never opens a running turn", () => {
    const previewable = file("previewable", "report.pdf", {
      turn_id: "current-turn",
    })
    const conversation = {
      turns: [{ id: "current-turn", status: "running" }],
      artifacts: [
        file("unavailable", "draft.pdf", {
          turn_id: "current-turn",
          download_available: false,
        }),
        file("unsupported", "archive.bin", {
          turn_id: "current-turn",
          mime_type: "application/octet-stream",
        }),
        previewable,
      ],
    } as unknown as Conversation

    expect(
      findFirstCompletedTurnPreviewFile(conversation, "current-turn")
    ).toBeNull()
    conversation.turns![0]!.status = "completed"
    expect(
      findFirstCompletedTurnPreviewFile(conversation, "current-turn")
    ).toBe(previewable)
  })
})
