import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { createHash, randomUUID } from "node:crypto";
import { cp, mkdir, mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Readable } from "node:stream";
import { setTimeout as delay } from "node:timers/promises";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import JSZip from "jszip";
import { interactiveApplicationManifestSchema } from "@linksense/shared";
import { createPrismaClient } from "../../src/db.js";
import { LinkSenseRedis } from "../../src/adapters/redis.js";
import { ApplicationService } from "../../src/modules/applications/service.js";
import { ApplicationPublicationService } from "../../src/modules/applications/publication-service.js";
import { ApplicationInstallationService } from "../../src/modules/applications/installation-service.js";
import { ApplicationRuntimeInstallationService } from "../../src/modules/applications/runtime-installation-service.js";
import { ApplicationRuntimeGate } from "../../src/modules/applications/runtime-gate.js";
import { ApplicationCenterService } from "../../src/modules/applications/center-service.js";
import { ApplicationDistributionRepository } from "../../src/modules/applications/distribution-repository.js";
import { assertApplicationRuntimeCurrent } from "../../src/modules/applications/runtime-version.js";
import { AuditService } from "../../src/modules/audit/service.js";
import { serviceWorkspaceRelativePath } from "../../src/lib/user-runtime-paths.js";
import { convertApplicationInstallations, installationMigrationName } from "../../src/operations/application-installation-conversion.js";
import { convertApplicationEnvironments } from "../../src/operations/application-environment-conversion.js";
import { assertRuntimeLayoutReady } from "../../src/operations/runtime-layout-readiness.js";
import { verifyExternalRuntimeUpdates } from "./application-external-runtime-scenarios.js";

// Every database, Redis key and file below is disposable. Never load application .env.
const execute = promisify(execFile);
const repositoryRoot = fileURLToPath(new URL("../../../../", import.meta.url));
const root = await mkdtemp(join(tmpdir(), "linksense-installations-"));
const names: string[] = [];
const docker = async (...args: string[]) => (await execute("docker", args, { timeout: 30_000 })).stdout.trim();
let db: ReturnType<typeof createPrismaClient> | undefined;
let redis: LinkSenseRedis | undefined;
let otherRedis: LinkSenseRedis | undefined;
try {
  const name = `linksense-installation-test-${randomUUID()}`, password = randomUUID();
  await docker("run", "--rm", "--label", "com.linksense.test.disposable=true", "-d", "--name", name, "-p", "127.0.0.1::5432", "-e", "POSTGRES_DB=installation_test", "-e", `POSTGRES_PASSWORD=${password}`, "postgres:16-alpine"); names.push(name);
  const port = Number((await docker("port", name, "5432")).split(":").at(-1));
  for (let n = 0; ; n++) { try { await docker("exec", name, "pg_isready", "-h", "127.0.0.1", "-U", "postgres"); break; } catch (error) { if (n >= 50) throw error; await delay(100); } }
  const databaseUrl = `postgresql://postgres:${password}@127.0.0.1:${port}/installation_test`;
  const migrations = join(repositoryRoot, "prisma/migrations"), historical = join(root, "migrations");
  for (const entry of await readdir(migrations, { withFileTypes: true })) if (!entry.isDirectory() || entry.name < installationMigrationName) await cp(join(migrations, entry.name), join(historical, entry.name), { recursive: true });
  const migrate = async (path: string) => execute("pnpm", ["exec", "prisma", "migrate", "deploy", "--config", "apps/api/test/integration/prisma.config.ts"], { cwd: repositoryRoot, timeout: 120_000, maxBuffer: 4_000_000, env: { ...process.env, DATABASE_URL: databaseUrl, LINKSENSE_TEST_MIGRATIONS_PATH: path } });
  await migrate(historical);
  db = createPrismaClient(databaseUrl); const prisma = db;
  const [creator, recipient, centerUser] = await Promise.all(["creator", "recipient", "center-user"].map(name => prisma.user.create({ data: { name, email: `${name}@example.test`, status: "active", role: "user" } })));
  assert(creator && recipient && centerUser);
  const actor = (id: string) => ({ id, role: "user" as const, status: "active" as const });
  const owner = actor(creator.id), user = actor(recipient.id), visitor = actor(centerUser.id);
  const legacy = await prisma.application.create({ data: { ownerId: creator.id, name: "Legacy", instructions: "Legacy instructions" } });
  const legacyVersionId = randomUUID();
  const legacyDefinition = JSON.stringify({ schemaVersion: 1, name: legacy.name, kind: "standard", instructions: "Previously shared instructions", usageInstructions: "", model: null, reasoningEffort: null, interactivePackageId: null, capabilities: [], knowledgeBaseIds: [], mcpServerIds: [] });
  await prisma.$executeRaw`INSERT INTO application_versions(id,application_id,version_number,version_label,definition_json,assets_ready,created_by) VALUES (${legacyVersionId}::uuid,${legacy.id}::uuid,1,'1.0.0',${legacyDefinition}::jsonb,true,${creator.id}::uuid)`;
  await prisma.application.update({ where: { id: legacy.id }, data: { publishedVersionId: legacyVersionId } });
  const userDataRoot = join(root, "users"), capabilityRoot = join(userDataRoot, ".capabilities");
  const oldWorkspace = `${creator.id}/home/workspace`;
  const legacyTask = await prisma.conversation.create({ data: { ownerId: creator.id, applicationId: legacy.id, title: "Legacy task", workspaceRelPath: oldWorkspace, runtimeGeneration: randomUUID(), titleSource: "manual", archiveStatus: "active", applicationNameSnapshot: "Fixture application" } });
  await mkdir(join(userDataRoot, oldWorkspace), { recursive: true });
  await mkdir(join(userDataRoot, creator.id, "home/.codex/sessions"), { recursive: true });
  await writeFile(join(userDataRoot, oldWorkspace, "keep.txt"), "User work retained");
  await writeFile(join(userDataRoot, creator.id, "home/.codex/auth.json"), '{"fixture":"existing-login"}');
  const legacyConsumer = await prisma.conversation.create({ data: { ownerId: recipient.id, applicationId: legacy.id, title: "Existing service use", workspaceRelPath: `${recipient.id}/home/workspace`, runtimeGeneration: randomUUID(), titleSource: "manual", archiveStatus: "active", applicationNameSnapshot: legacy.name } });
  await mkdir(join(userDataRoot, legacyConsumer.workspaceRelPath), { recursive: true });
  await writeFile(join(userDataRoot, legacyConsumer.workspaceRelPath, "service-work.txt"), "Service user data");
  await prisma.applicationGrant.create({ data: { applicationId: legacy.id, granteeType: "user", userId: recipient.id, usageModes: ["service"], status: "active", grantedBy: creator.id } });
  const oldPageIds = [randomUUID(), randomUUID()];
  const legacyPreview = await prisma.application.create({ data: { ownerId: creator.id, name: "Legacy preview", instructions: "Current draft", kind: "interactive", developmentOnly: true, interactivePackageId: oldPageIds[1]! } });
  const oldPages = await Promise.all(["0.0.0-dev.1", "0.0.0-dev.2"].map((version, index) => prisma.interactiveApplicationPackage.create({ data: {
    id: oldPageIds[index]!, applicationId: legacyPreview.id, version, createdBy: creator.id, archiveSha256: "a".repeat(64), fileCount: 2, expandedBytes: 1,
    manifestJson: interactiveApplicationManifestSchema.parse({ schema_version: 1, id: "historical-preview", name: "Legacy preview", version, sdk_version: 1, instructions: `Snapshot ${version}` }),
  } })));
  const historicalObjects = new Map<string, Buffer>();
  for (const page of oldPages) {
    for (const [path, contentType, content] of [["manifest.json", "application/json", JSON.stringify(page.manifestJson)], ["index.html", "text/html", `<h1>${page.version}</h1>`]]) {
      const data = Buffer.from(content!), objectKey = `${page.id}/${path}`;
      historicalObjects.set(objectKey, data);
      await prisma.interactiveApplicationAsset.create({ data: { packageId: page.id, path: path!, objectKey, contentType: contentType!, byteSize: data.length, sha256: createHash("sha256").update(data).digest("hex") } });
    }
    await prisma.interactiveApplicationPackage.update({ where: { id: page.id }, data: { expandedBytes: [...historicalObjects.entries()].filter(([key]) => key.startsWith(page.id)).reduce((sum, [, data]) => sum + data.length, 0) } });
  }
  const oldTest = await prisma.conversation.create({ data: { ownerId: creator.id, applicationId: legacyPreview.id, interactiveApplicationPackageId: oldPages[0]!.id, title: "Used test", workspaceRelPath: oldWorkspace, runtimeGeneration: randomUUID(), titleSource: "manual", archiveStatus: "active", applicationNameSnapshot: legacyPreview.name } });
  await prisma.conversationTurn.create({ data: { conversationId: oldTest.id, sequenceNo: 1, submittedBy: creator.id, submitMode: "normal", capabilityGeneration: "a".repeat(64), capabilitiesJson: [], startedAt: new Date(), completedAt: new Date(), status: "completed", codexThreadId: randomUUID(), codexTurnId: randomUUID() } });
  await prisma.application.update({ where: { id: legacyPreview.id }, data: { interactivePackageId: oldPages[1]!.id } });
  const unusedPreview = await prisma.application.create({ data: { ownerId: creator.id, name: "Never tested", instructions: "Preview only", developmentOnly: true } });
  await migrate(migrations);
  await assert.rejects(assertRuntimeLayoutReady(prisma, userDataRoot), /MIGRATION_APPLICATION_ENVIRONMENT_REQUIRED/);
  await convertApplicationEnvironments({ prisma, userDataRoot, outputRoot: join(root, "environment-backup"), apply: true });
  assert.deepEqual(await convertApplicationInstallations({ prisma, capabilityRoot, apply: true }), { owners: 1, consumers: 1, debug: 1, applied: true });
  assert.deepEqual(await convertApplicationInstallations({ prisma, capabilityRoot, apply: true }), { owners: 0, consumers: 0, debug: 0, applied: true });
  await assertRuntimeLayoutReady(prisma, userDataRoot);
  const converted = await prisma.conversation.findUniqueOrThrow({ where: { id: legacyTask.id } });
  assert.equal(converted.workspaceRelPath, serviceWorkspaceRelativePath(creator.id, legacy.id));
  assert.equal(await readFile(join(userDataRoot, converted.workspaceRelPath, "imports/personal/workspace/keep.txt"), "utf8"), "User work retained");
  assert.equal(await readFile(join(userDataRoot, oldWorkspace, "keep.txt"), "utf8"), "User work retained");
  assert.equal(await readFile(join(userDataRoot, creator.id, "services", legacy.id, "home/.codex/auth.json"), "utf8"), '{"fixture":"existing-login"}');
  console.log("PASS historical migration: stable task ID, original files and authentication retained; repeat upgrade is inert");

  const redisName = `linksense-installation-redis-${randomUUID()}`;
  await docker("run", "--rm", "--label", "com.linksense.test.disposable=true", "-d", "--name", redisName, "-p", "127.0.0.1::6379", "redis:7-alpine"); names.push(redisName);
  const redisPort = Number((await docker("port", redisName, "6379")).split(":").at(-1));
  const config = { redisUrl: `redis://127.0.0.1:${redisPort}` };
  redis = new LinkSenseRedis(config as never); otherRedis = new LinkSenseRedis(config as never);
  await redis.connect(); await otherRedis.connect();
  const closed: string[] = [];
  const gate = new ApplicationRuntimeGate(prisma, redis, async (_owner, task) => { closed.push(task); });
  const competingGate = new ApplicationRuntimeGate(prisma, otherRedis, async () => {});
  const objects = new Map(historicalObjects);
  const assets = { put: async (key: string, bytes: Buffer) => { objects.set(key, bytes); }, get: async (key: string) => { const data = objects.get(key); if (!data) throw new Error("missing fixture asset"); return Readable.from([data]); }, remove: async (key: string) => { objects.delete(key); } };
  const publications = new ApplicationPublicationService(prisma, capabilityRoot, assets);
  const copies = new ApplicationInstallationService(prisma, capabilityRoot, publications, gate);
  const selections = new ApplicationRuntimeInstallationService(prisma, publications, gate);
  const models = { resolveRuntime: async () => { throw new Error("unused model"); }, resolveRuntimeForSelection: async () => { throw new Error("unused model"); }, resolveModelTransitionRuntime: async () => { throw new Error("unused model"); } };
  const app = new ApplicationService(prisma, models, new AuditService(prisma), { resolveForCapability: async (userId, capabilityId) => ({ ok: true, environment: {}, usageReceipt: { userId, capabilityId, credentialIds: [] } }) }, undefined, assets, publications, copies, selections);
  const center = new ApplicationCenterService(new ApplicationDistributionRepository(prisma), publications, new AuditService(prisma), app);
  assert.equal((await app.resolveRuntime(creator.id, legacy.id)).instructions, "Legacy instructions");
  assert.equal((await app.resolveRuntime(recipient.id, legacy.id)).instructions, "Previously shared instructions");
  assert.equal((await app.resolveRuntime(creator.id, legacyPreview.id)).interactivePackageId, oldPages[0]!.id);
  assert.equal((await prisma.application.findUniqueOrThrow({ where: { id: legacyPreview.id } })).interactivePackageId, oldPages[1]!.id);
  assert.equal(await prisma.applicationRuntimeInstallation.count({ where: { applicationId: unusedPreview.id } }), 0);
  assert.equal(await readFile(join(userDataRoot, serviceWorkspaceRelativePath(recipient.id, legacy.id), "imports/personal/workspace/service-work.txt"), "utf8"), "Service user data");
  const skillId = randomUUID(), source = join(capabilityRoot, "source");
  await mkdir(source, { recursive: true });
  await writeFile(join(source, "SKILL.md"), "---\nname: task-skill\ndescription: Fixture skill\n---\nOld content");
  await prisma.capability.create({ data: { id: skillId, ownerId: creator.id, type: "skill", name: "task-skill", slug: "task-skill", sourceType: "local", storagePath: "source", status: "active", installedBy: creator.id } });
  const application = await prisma.application.create({ data: { ownerId: creator.id, name: "Reports", description: "Published description", instructions: "Instructions one" } });
  await prisma.applicationCapability.create({ data: { applicationId: application.id, capabilityId: skillId, capabilityNameSnapshot: "task-skill", capabilityTypeSnapshot: "skill", selectionOrder: 0 } });
  await assert.rejects(app.resolveRuntime(creator.id, application.id), { code: "APPLICATION_INSTALLATION_REQUIRED" });
  const v1 = await app.publish(owner, application.id, { version_number: "1.0.0", usage_instructions: "Guide one" }); assert(v1.version_id);
  for (const invalid of ["1.0.0", "0.9.0", "1.0", "1.1.0+build.2"]) await assert.rejects(app.publish(owner, application.id, { version_number: invalid, usage_instructions: "" }));
  await app.share(owner, application.id, { version_number: "1.0.0", usage_instructions: "", target: { grantee_type: "user", user_id: recipient.id, usage_modes: ["service", "install"] } }, {});
  await assert.rejects(app.resolveRuntime(recipient.id, application.id), { code: "APPLICATION_INSTALLATION_REQUIRED" });
  await app.installService(user, application.id, "direct", v1.version_id, {});
  const release1 = await center.submit(owner, application.id, { version_number: "1.0.0", usage_instructions: "", usage_modes: ["service", "install"], release_notes: "Initial" }, {});
  await center.review({ ...owner, role: "admin" }, release1.id, { decision: "approved", comment: "" }, {});
  await app.installService(visitor, application.id, "center", v1.version_id, {});
  const copiedId = await copies.install(recipient.id, application.id, { name: "My reports", channel: "direct", version_id: v1.version_id });
  const copiedCard = (await app.catalog(user, { state: "all", limit: 100 })).items.find(item => item.type === "application" && item.application.id === copiedId);
  assert(copiedCard?.type === "application"); assert.equal(copiedCard.application.name, "My reports");
  await prisma.application.update({ where: { id: copiedId }, data: { instructions: "Local edit to replace" } });
  const task = await prisma.conversation.create({ data: { ownerId: recipient.id, applicationId: application.id, applicationVersionId: v1.version_id, workspaceRelPath: serviceWorkspaceRelativePath(recipient.id, application.id), runtimeGeneration: randomUUID(), titleSource: "manual", archiveStatus: "active", applicationNameSnapshot: "Fixture application", title: "Existing task" } });
  const file = join(userDataRoot, task.workspaceRelPath, "keep.txt"); await mkdir(join(userDataRoot, task.workspaceRelPath), { recursive: true }); await writeFile(file, "Retained");
  await prisma.application.update({ where: { id: application.id }, data: { instructions: "Instructions two", name: "Reports two" } });
  const frozenCard = (await app.catalog(owner, { state: "all", limit: 100 })).items.find(item => item.type === "application" && item.application.id === application.id);
  assert(frozenCard?.type === "application");
  assert.equal(frozenCard.application.name, "Reports");
  await writeFile(join(source, "SKILL.md"), "---\nname: task-skill\ndescription: Fixture skill\n---\nNew content, same plugin version");
  const v2 = await app.publish(owner, application.id, { version_number: "1.1.0", usage_instructions: "Guide two" }); assert(v2.version_id);
  assert.equal((await app.resolveRuntime(creator.id, application.id)).applicationVersionId, v2.version_id);
  assert.equal((await app.resolveRuntime(recipient.id, application.id)).applicationVersionId, v1.version_id);
  assert.equal((await app.resolveRuntime(centerUser.id, application.id, "center")).applicationVersionId, v1.version_id);
  assert.equal((await prisma.application.findUniqueOrThrow({ where: { id: application.id } })).publishedVersionId, v1.version_id);
  assert.equal((await prisma.applicationListing.findUniqueOrThrow({ where: { applicationId: application.id } })).currentReleaseId, release1.id);
  await verifyExternalRuntimeUpdates({ prisma, applications: app, publications, competingGate, applicationId: application.id,
    creatorId: creator.id, recipientId: recipient.id, oldVersionId: v1.version_id, newVersionId: v2.version_id, userDataRoot, capabilityRoot });
  await app.share(owner, application.id, { version_number: "1.1.0", usage_instructions: "", target: null }, {});
  assert.equal((await app.resolveRuntime(recipient.id, application.id)).applicationVersionId, v1.version_id);
  const oldRuntime = await app.resolveRuntime(recipient.id, application.id);
  await gate.start(recipient.id, application.id, async () => {
    await competingGate.start(recipient.id, application.id, async () => {});
    await assert.rejects(app.installService(user, application.id, "direct", v2.version_id!, {}), { code: "APPLICATION_RUNTIME_BUSY" });
  });
  await gate.change(recipient.id, application.id, async () => {
    await assert.rejects(competingGate.start(recipient.id, application.id, async () => {}), { code: "APPLICATION_RUNTIME_UPDATING" });
    await competingGate.start(creator.id, application.id, async () => {});
    await competingGate.start(recipient.id, randomUUID(), async () => {});
  });
  const turn = await prisma.conversationTurn.create({ data: { conversationId: task.id, sequenceNo: 1, submittedBy: creator.id, submitMode: "normal", capabilityGeneration: "a".repeat(64), capabilitiesJson: [], startedAt: new Date(), status: "running", codexThreadId: randomUUID(), codexTurnId: randomUUID() } });
  const secondTask = await prisma.conversation.create({ data: { ownerId: recipient.id, applicationId: application.id, title: "Concurrent task", workspaceRelPath: task.workspaceRelPath, runtimeGeneration: randomUUID(), titleSource: "manual", archiveStatus: "active", applicationNameSnapshot: "Fixture application" } });
  const secondTurn = await prisma.conversationTurn.create({ data: { conversationId: secondTask.id, sequenceNo: 1, submittedBy: recipient.id, submitMode: "normal", capabilityGeneration: "a".repeat(64), capabilitiesJson: [], startedAt: new Date(), status: "running", codexThreadId: randomUUID(), codexTurnId: randomUUID() } });
  await assert.rejects(app.installService(user, application.id, "direct", v2.version_id, {}), { code: "APPLICATION_RUNTIME_BUSY" });
  await prisma.conversationTurn.update({ where: { id: turn.id }, data: { status: "completed", completedAt: new Date() } });
  await assert.rejects(app.installService(user, application.id, "direct", v2.version_id, {}), { code: "APPLICATION_RUNTIME_BUSY" });
  await prisma.conversationTurn.update({ where: { id: secondTurn.id }, data: { status: "completed", completedAt: new Date() } });
  const startIntent = await prisma.conversationTurnStartIntent.create({ data: { projectionTurnId: randomUUID(), ownerId: recipient.id, conversationId: secondTask.id, runtimeGeneration: secondTask.runtimeGeneration, capabilityGeneration: "a".repeat(64), applicationId: application.id, applicationUpdatedAt: application.updatedAt, applicationInstructions: application.instructions, inputText: "Queued start", submitMode: "normal" } });
  await assert.rejects(app.installService(user, application.id, "direct", v2.version_id, {}), { code: "APPLICATION_RUNTIME_BUSY" });
  await prisma.conversationTurnStartIntent.delete({ where: { projectionTurnId: startIntent.projectionTurnId } });
  await app.installService(user, application.id, "direct", v2.version_id, {});
  const current = await app.resolveRuntime(recipient.id, application.id);
  assert.equal(current.applicationVersionId, v2.version_id);
  assert.equal(await readFile(join(capabilityRoot, current.publishedCapabilities[0]!.storagePath, "SKILL.md"), "utf8"), "---\nname: task-skill\ndescription: Fixture skill\n---\nNew content, same plugin version");
  await prisma.$transaction(tx => assertApplicationRuntimeCurrent(tx, recipient.id, current));
  await assert.rejects(prisma.$transaction(tx => assertApplicationRuntimeCurrent(tx, recipient.id, oldRuntime)), { code: "APPLICATION_INSTALLATION_REQUIRED" });
  assert.equal(await readFile(file, "utf8"), "Retained"); assert(closed.includes(task.id));
  assert.equal((await app.resolveRuntime(centerUser.id, application.id, "center")).applicationVersionId, v1.version_id);
  const release2 = await center.submit(owner, application.id, { version_number: "1.1.0", usage_instructions: "", usage_modes: ["service", "install"], release_notes: "Update" }, {});
  assert.equal((await prisma.applicationListing.findUniqueOrThrow({ where: { applicationId: application.id } })).currentReleaseId, release1.id);
  await center.review({ ...owner, role: "admin" }, release2.id, { decision: "approved", comment: "" }, {});
  await app.installService(visitor, application.id, "center", v2.version_id, {});
  assert.equal(await copies.install(recipient.id, application.id, { name: "Ignored second name", channel: "center", version_id: v2.version_id }), copiedId);
  assert.equal((await app.resolveRuntime(recipient.id, copiedId)).instructions, "Instructions two");
  assert.equal(await prisma.applicationInstallation.count({ where: { ownerId: recipient.id, sourceApplicationId: application.id } }), 1);
  assert.equal(await copies.install(recipient.id, application.id, { name: "Again", channel: "direct", version_id: v2.version_id }), copiedId);
  console.log("PASS creator publication, explicit sharing/approval/install, copy overwrite, stable identity and cross-instance Redis exclusion");

  const zip = async (version: string) => { const archive = new JSZip(); archive.file("manifest.json", JSON.stringify({ schema_version: 1, id: "debug-app", name: "Debug application", version, sdk_version: 1, instructions: `Page ${version}` })); archive.file("index.html", `<h1>${version}</h1>`); return archive.generateAsync({ type: "nodebuffer" }); };
  const preview = await app.importInteractive(owner, await zip("0.0.0-dev.1"), {}, [], { developmentOnly: true });
  assert.equal(await prisma.applicationRuntimeInstallation.count({ where: { applicationId: preview.id } }), 0);
  await app.prepareDebugRuntime(creator.id, preview.id, preview.interactive_package!.id);
  const firstDebug = await app.resolveRuntime(creator.id, preview.id);
  const debugTask = await prisma.conversation.create({ data: { ownerId: creator.id, applicationId: preview.id, interactiveApplicationPackageId: preview.interactive_package!.id, title: "Debug", workspaceRelPath: serviceWorkspaceRelativePath(creator.id, preview.id), runtimeGeneration: randomUUID(), titleSource: "manual", archiveStatus: "active", applicationNameSnapshot: "Fixture application" } });
  const debugTurn = await prisma.conversationTurn.create({ data: { conversationId: debugTask.id, sequenceNo: 1, submittedBy: creator.id, submitMode: "normal", capabilityGeneration: "a".repeat(64), capabilitiesJson: [], startedAt: new Date(), status: "running", codexThreadId: randomUUID(), codexTurnId: randomUUID() } });
  await app.prepareDebugRuntime(creator.id, preview.id, preview.interactive_package!.id);
  await gate.start(creator.id, preview.id, async () => {});
  const nextPreview = await app.updateInteractivePackage(owner, preview.id, await zip("0.0.0-dev.2"), {});
  assert.equal((await app.resolveRuntime(creator.id, preview.id)).applicationVersionId, firstDebug.applicationVersionId);
  await assert.rejects(app.prepareDebugRuntime(creator.id, preview.id, nextPreview.interactive_package!.id), { code: "APPLICATION_DEVELOPMENT_TEST_BUSY" });
  // A running debug task does not prevent formal publication or normal starts.
  await prisma.applicationCapability.deleteMany({ where: { applicationId: application.id } });
  const v3 = await app.publish(owner, application.id, { version_number: "1.2.0", usage_instructions: "" }); assert(v3.version_id);
  await gate.start(creator.id, application.id, async () => {});
  await prisma.conversationTurn.update({ where: { id: debugTurn.id }, data: { status: "completed", completedAt: new Date() } });
  const formalTask = await prisma.conversation.create({ data: { ownerId: creator.id, applicationId: application.id, title: "Formal still running", workspaceRelPath: serviceWorkspaceRelativePath(creator.id, application.id), runtimeGeneration: randomUUID(), titleSource: "manual", archiveStatus: "active", applicationNameSnapshot: "Fixture application" } });
  const formalTurn = await prisma.conversationTurn.create({ data: { conversationId: formalTask.id, sequenceNo: 1, submittedBy: creator.id, submitMode: "normal", capabilityGeneration: "a".repeat(64), capabilitiesJson: [], startedAt: new Date(), status: "running", codexThreadId: randomUUID(), codexTurnId: randomUUID() } });
  await app.prepareDebugRuntime(creator.id, preview.id, nextPreview.interactive_package!.id);
  assert.equal((await prisma.conversationTurn.findUniqueOrThrow({ where: { id: formalTurn.id } })).status, "running");
  await assert.rejects(app.publish(owner, application.id, { version_number: "1.3.0", usage_instructions: "" }), { code: "APPLICATION_RUNTIME_BUSY" });
  await prisma.conversationTurn.update({ where: { id: formalTurn.id }, data: { status: "completed", completedAt: new Date() } });
  assert.notEqual((await app.resolveRuntime(creator.id, preview.id)).applicationVersionId, firstDebug.applicationVersionId);
  assert.equal((await app.resolveRuntime(creator.id, application.id)).capabilityIds.length, 0);
  // Publication integrity failure preserves recipients' selected version.
  await app.share(owner, application.id, { version_number: "1.2.0", usage_instructions: "", target: null }, {});
  const before = await app.resolveRuntime(recipient.id, application.id);
  await selections.install(recipient.id, application.id, "direct", v3.version_id, async () => { throw new Error("Unavailable credential"); }).then(() => assert.fail("should reject"), error => assert.equal(error.message, "Unavailable credential"));
  assert.equal((await app.resolveRuntime(recipient.id, application.id)).applicationVersionId, before.applicationVersionId);
  await app.installService(user, application.id, "direct", v3.version_id, {});
  assert.equal((await app.resolveRuntime(recipient.id, application.id)).capabilityIds.length, 0);
  await assert.rejects(app.prepareDebugRuntime(recipient.id, preview.id, nextPreview.interactive_package!.id).then(() => app.resolvePreviewRuntime(recipient.id, preview.id)), { code: "APPLICATION_NOT_FOUND" });
  console.log("PASS isolated debug snapshots, concurrent same-snapshot tests, formal publication during debug, failed update protection and removed skills");
} finally {
  await otherRedis?.close(); await redis?.close(); await db?.$disconnect();
  for (const name of names.reverse()) await docker("rm", "--force", "--volumes", name);
  await rm(root, { recursive: true, force: true });
}
