# syntax=docker/dockerfile:1.7
ARG UPSTREAM_IMAGE=postgres:16-alpine
FROM golang:1.27.1-alpine@sha256:8a5910f31396cd4d89662f56c68b3ae31d374308270a1c3bd96672ee5ed43414 AS gosu
RUN CGO_ENABLED=0 go install github.com/tianon/gosu@6456aaa0f3c854d199d0f037f068eb97515b7513 \
  && /go/bin/gosu --version
FROM ${UPSTREAM_IMAGE}
ARG SECURITY_REBUILD_ID=local
RUN test -n "$SECURITY_REBUILD_ID" && apk upgrade --no-cache
COPY --from=gosu --chmod=0755 /go/bin/gosu /usr/local/bin/gosu
COPY --from=gosu /usr/local/go/LICENSE /usr/share/licenses/gosu-go/LICENSE
